version: '3'
services:
  node:
    image: node:14  # Update to use a newer Node version if possible
    working_dir: /app
    volumes:
      - .:/app:delegated
    command: npm run build  # Specify a default command if needed, or use it to run node services

  ruby:
    build: .
    working_dir: /app
    ports:
      - "4000:4000"
    volumes:
      - .:/app:delegated
    command: bundle exec jekyll serve --host 0.0.0.0
